name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ruanjanau
          outputs: |
            ./output/snake.svg

      - name: Push Snake Animation to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: generate snake.svg"
          add: "output/snake.svg"
